export enum ActionTypes {
  FETCH_EVENTS = 'FETCH_EVENTS',
  FETCH_OPTIONS = 'FETCH_OPTIONS',
  LOADING = 'LOADING',
  TOGGLE_THEME = 'TOGGLE_THEME',
  SET_THEME = 'SET_THEME',
  SET_USER = 'SET_USER',
  REMOVE_USER = 'REMOVE_USER',
}
